/********************************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

//! Field consumer implementation for Lola runtime — the `WithNotifier` (change-notification
//! subscription) half of Field support. Field get/set (`WithGetter`/`WithSetter`) are NOT here: per
//! `score_com_concept::field_concept`'s own doc comment, they are modelled as `MethodCaller`-based
//! callers (`R::FieldGetCaller<T>`/`R::FieldSetCaller<T>`, generated by the `interface!` macro as
//! separate `{name}_get`/`{name}_set` consumer struct fields) and implemented in `method.rs`
//! (`LolaFieldGetCaller`/`LolaFieldSetCaller`) instead, since they reuse the Method call
//! infrastructure end to end.
//!
//! Implemented this fork, 2026-09-08 (previously `todo!()` placeholders — see
//! `docs/design-notes.md` §1.4 for this fork's earlier Method<T> FFI work that this builds on).
//!
//! Confirmed via the real C++ headers (`score/mw/com/impl/proxy_field.h`,
//! `plumbing/proxy_field_binding_factory_impl.h`) that a Field's `WithNotifier` capability is, on the
//! C++ side, a genuine `ProxyEvent<T>`/`ProxyEventBase` under the hood — `ProxyFieldImpl` composes one
//! via the ordinary `ProxyEventBindingFactory` (tagged `ServiceElementType::FIELD`, but otherwise
//! identical machinery to a plain event), registered under the field's own bare member name (e.g.
//! `left_tire`, not `left_tire_get`/`_set`). So `LolaFieldSubscriber`/`LolaFieldSubscription` below are
//! pure delegating wrappers around `consumer.rs`'s already-fully-implemented
//! `LolaSubscribableImpl<T, B>`/`LolaSubscriberImpl<T, B>` — no new FFI was needed for the base
//! `Subscriber`/`Subscription` methods, only for the two extra `FieldSubscription`-only queries
//! (`get_free_sample_count`/`get_num_new_samples_available`), which map onto `ProxyEventBase`'s own
//! `GetFreeSampleCount()`/`GetNumNewSamplesAvailable()` (new FFI added in `bridge_ffi.rs`/
//! `bridge_ffi_lola.rs`/`registry_bridge_macro.cpp`, exposed here via new `pub(crate)` methods on
//! `LolaSubscriberImpl` itself, see `consumer.rs`).
//!
//! Verification status: same caveat as the rest of this fork's Method<T>/Field<T> work — completely
//! unverified by any compiler (no Cargo.toml in this repository, no Bazel in this sandbox).

use core::fmt::Debug;
use core::future::Future;

use bridge_ffi_rs::FFIBridge;
use futures::stream::Stream;
use score_com_concept::{
    CommData, FieldSubscriber, FieldSubscription, Result, SampleContainer, Subscriber, Subscription,
};

use crate::consumer::{LolaSample, LolaSubscriberImpl};
use crate::{LolaConsumerInfo, LolaRuntimeImpl, LolaSubscribableImpl};

/// Field subscriber type which implements the FieldSubscriber trait for Lola runtime.
/// Pure delegating wrapper around `LolaSubscribableImpl<T, B>` (see this file's module doc comment).
pub struct LolaFieldSubscriber<T: CommData + Debug, B: FFIBridge> {
    inner: LolaSubscribableImpl<T, B>,
}

/// Marker implementation of FieldSubscriber trait.
/// Field get/set are exposed as async MethodCaller-based wrappers on the consumer struct
/// generated by the interface! macro; they are not part of FieldSubscriber itself.
impl<T: CommData + Debug, B: FFIBridge> FieldSubscriber<T, LolaRuntimeImpl<B>>
    for LolaFieldSubscriber<T, B>
{
}

/// Implementation of Subscriber trait which provides `new` and `subscribe` methods for LolaFieldSubscriber.
impl<T: CommData + Debug, B: FFIBridge> Subscriber<T, LolaRuntimeImpl<B>>
    for LolaFieldSubscriber<T, B>
{
    type Subscription = LolaFieldSubscription<T, B>;

    fn new(identifier: &'static str, instance_info: LolaConsumerInfo<B>) -> Result<Self> {
        Ok(Self {
            inner: LolaSubscribableImpl::new(identifier, instance_info)?,
        })
    }

    fn subscribe(self, max_num_samples: usize) -> Result<Self::Subscription> {
        Ok(LolaFieldSubscription {
            inner: self.inner.subscribe(max_num_samples)?,
        })
    }
}

/// FieldSubscription type which provides data receiving APIs and unsubscribe method.
/// Pure delegating wrapper around `LolaSubscriberImpl<T, B>` (see this file's module doc comment).
pub struct LolaFieldSubscription<T: CommData + Debug, B: FFIBridge> {
    inner: LolaSubscriberImpl<T, B>,
}

impl<T: CommData + Debug, B: FFIBridge> FieldSubscription<T, LolaRuntimeImpl<B>>
    for LolaFieldSubscription<T, B>
{
    fn get_free_sample_count(&self) -> Result<usize> {
        self.inner.get_free_sample_count()
    }

    fn get_num_new_samples_available(&self) -> Result<usize> {
        self.inner.get_num_new_samples_available()
    }
}

/// Implementation of Subscription trait which provides receiving APIs.
impl<T: CommData + Debug, B: FFIBridge> Subscription<T, LolaRuntimeImpl<B>>
    for LolaFieldSubscription<T, B>
{
    type Subscriber = LolaFieldSubscriber<T, B>;
    type Sample<'a>
        = LolaSample<T, B>
    where
        Self: 'a;

    fn unsubscribe(self) -> Self::Subscriber {
        LolaFieldSubscriber {
            inner: self.inner.unsubscribe(),
        }
    }

    fn try_receive<'a>(
        &'a self,
        scratch: &'_ mut SampleContainer<Self::Sample<'a>>,
        max_samples: usize,
    ) -> Result<usize> {
        self.inner.try_receive(scratch, max_samples)
    }

    #[allow(clippy::manual_async_fn)]
    fn cancellable_receive<'a>(
        &'a self,
        scratch: SampleContainer<Self::Sample<'a>>,
        new_samples: usize,
        max_samples: usize,
        cancellation: impl Future<Output = ()> + Send + 'static,
    ) -> impl Future<Output = (SampleContainer<Self::Sample<'a>>, Result<usize>)> + 'a {
        self.inner
            .cancellable_receive(scratch, new_samples, max_samples, cancellation)
    }

    fn to_stream<'a>(&'a mut self) -> impl Stream<Item = Result<Self::Sample<'a>>> + Unpin + 'a {
        self.inner.to_stream()
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use core::ptr::NonNull;

    use bridge_ffi_mock::{MockFFIBridge, MockPointerAllocator, SharedMockBridge};
    use bridge_ffi_rs::{ProxyBase, ProxyEventBase, TypeOperations, TypeOperationsManager};
    use crate::consumer::LolaSubscribableImpl;

    #[derive(Debug)]
    #[repr(C)]
    struct FieldTestData {
        #[allow(dead_code)]
        value: i32,
    }

    unsafe impl score_com_concept::Reloc for FieldTestData {}

    impl score_com_concept::CommData for FieldTestData {
        const ID: &'static str = "FieldTestData";
    }

    /// PR #6's test plan item 3: a Field subscription receiving a change notification. Only
    /// `LolaFieldSubscriber`/`LolaFieldSubscription` themselves are new for Field — they're pure
    /// delegating wrappers (see this file's module doc comment) around `consumer.rs`'s
    /// already-tested `LolaSubscribableImpl`/`LolaSubscriberImpl` — so this exercises the same
    /// subscribe → try_receive path `consumer.rs::test::test_event_try_receive` already covers for
    /// plain events, plus the two genuinely new query FFI calls (`proxy_event_get_free_sample_count`/
    /// `proxy_event_get_num_new_samples_available`) that only `FieldSubscription` exposes.
    #[test]
    fn test_field_subscription_receives_change_notification() {
        let mut mock = MockFFIBridge::new();
        let mut seq = mockall::Sequence::new();

        let proxy_alloc = MockPointerAllocator::<ProxyBase>::new();
        let event_alloc = MockPointerAllocator::<ProxyEventBase>::new();
        let type_ops_alloc = MockPointerAllocator::<TypeOperations>::new();

        let prox = proxy_alloc.clone();
        mock.expect_create_proxy()
            .in_sequence(&mut seq)
            .returning(move |_, _| prox.allocate());
        let evt = event_alloc.clone();
        mock.expect_get_event_from_proxy()
            .in_sequence(&mut seq)
            .returning(move |_, _, _| evt.allocate());
        mock.expect_subscribe_to_event()
            .in_sequence(&mut seq)
            .returning(|_, _| true);
        mock.expect_get_type_ops_instance()
            .in_sequence(&mut seq)
            .returning(move |_, _| {
                Some(TypeOperationsManager::new(
                    NonNull::new(type_ops_alloc.allocate()).expect("Failed to allocate TypeOperations for mock"),
                ))
            });

        // New for Field: not exercised by any existing plain-Event test.
        mock.expect_proxy_event_get_free_sample_count()
            .in_sequence(&mut seq)
            .returning(|_| 4);
        mock.expect_proxy_event_get_num_new_samples_available()
            .in_sequence(&mut seq)
            .returning(|_| Some(1));

        mock.expect_get_samples_from_event()
            .in_sequence(&mut seq)
            .returning(|_, _, _, _| 1);
        mock.expect_set_event_receive_handler()
            .in_sequence(&mut seq)
            .returning(|_, _| true);
        mock.expect_clear_event_receive_handler()
            .in_sequence(&mut seq)
            .returning(|_| ());

        let evt_cleanup = event_alloc.clone();
        mock.expect_unsubscribe_to_event()
            .in_sequence(&mut seq)
            .returning(move |ptr| {
                assert!(evt_cleanup.free(ptr), "unsubscribe_to_event called with unknown pointer");
            });
        let prox_cleanup = proxy_alloc.clone();
        mock.expect_destroy_proxy()
            .in_sequence(&mut seq)
            .returning(move |ptr| {
                assert!(prox_cleanup.free(ptr), "destroy_proxy called with unknown pointer");
            });

        let bridge = SharedMockBridge::new(mock);
        let subscribable = LolaFieldSubscriber::<FieldTestData, SharedMockBridge> {
            inner: LolaSubscribableImpl::new_for_test("TestField", bridge, "TestInterface")
                .expect("LolaSubscribableImpl::new_for_test should succeed with mock create_proxy"),
        };

        let subscription = subscribable
            .subscribe(5)
            .expect("subscribe should succeed with proper mock setup");

        // Field-only queries.
        assert_eq!(
            subscription
                .get_free_sample_count()
                .expect("get_free_sample_count should succeed"),
            4
        );
        assert_eq!(
            subscription
                .get_num_new_samples_available()
                .expect("get_num_new_samples_available should succeed"),
            1
        );

        // The actual "change notification" round trip.
        let mut sample_container = SampleContainer::new(5);
        let count = subscription
            .try_receive(&mut sample_container, 5)
            .expect("try_receive should succeed with a valid mock event");
        assert_eq!(count, 1, "one sample (the field's change notification) should be returned");
    }
}
