/********************************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

// TODOs:
// 1.Get and Set methods for field it is enabled based on tag, do we want to keep same kind of mechanism
// or by default we will enable for user,
// -> we can keep it default enable as of now,
// and later we can add tag based mechanism if required because Interface side we need to check how we can do this
// 2. We are offering get method after subscrption async but before subscription it is sync,
// It is because subscribe API take the consumer instance by value and if we offer async get method then it will create issue with subscription.

// Note: We are using the event related trait as a base trait for where ever we have same common
// APIs or functionality, as of now there are derived from concept crate but
// we will create a module which will have common trait for event and field which will be used by both event and field as a super trait and
// for this we need to create marker trait for event.
//
// Note: Field get/set on the consumer side are modelled as MethodCaller-based callers so
// they reuse the full Method infrastructure (async futures, copy/zero-copy paths,
// MethodReturnSample<T>) instead of a separate field-specific design.
// The interface! macro generates `{name}_get: R::MethodCaller<(), T>` and
// `{name}_set: R::MethodCaller<(T,), T>` fields on the consumer struct, together
// with `get_{name}()` / `set_{name}()` async convenience wrappers.
// On the producer side, FieldPublisher keeps update() + register_set_handler() unchanged.

use crate::concept::{self, CommData, Result, Runtime, SampleMaybeUninit};
use std::fmt::Debug;

/// `FieldSubscriber` is used to subscribe to a field and receive update notifications.
/// It derives from `concept::Subscriber<T, R>` which provides the `subscribe()` method to
/// create a `FieldSubscription`.
///
/// Field get/set operations are NOT part of this trait. They are exposed on the consumer
/// struct as separate async method callers (`get_{name}()` / `set_{name}()`) generated by
/// the `interface!` macro, reusing the Method infrastructure.
pub trait FieldSubscriber<T: CommData + Debug, R: Runtime + ?Sized>:
    concept::Subscriber<T, R, Subscription: FieldSubscription<T, R>>
{
}

/// `FieldSubscription` provides the data-receiving APIs for an active field subscription
/// (after `FieldSubscriber::subscribe()` has been called). It derives from
/// `concept::Subscription<T, R>` which provides `try_receive`, `receive`,
/// `cancellable_receive`, and `to_stream`.
///
/// In addition to the base subscription APIs, a field subscription exposes:
/// - `get_num_new_samples_available()` — how many fresh samples are ready to receive.
/// - `get_free_sample_count()` — remaining capacity in the subscription buffer.
pub trait FieldSubscription<T: CommData + Debug, R: Runtime + ?Sized>:
    concept::Subscription<T, R>
{
    /// Returns the number of new samples a call to `try_receive` (given that
    /// `max_num_samples` does not restrict it) would currently provide.
    fn get_num_new_samples_available(&self) -> Result<usize>;

    /// Returns the number of sample slots that can still be filled before the subscription
    /// buffer overflows.
    fn get_free_sample_count(&self) -> Result<usize>;
}

/// FieldPublisher trait is used to publish a field and update the value of the field.
//  Note:  We can not use publisher trait from event because that contains the Send Method which is not correct semantic for field.
pub trait FieldPublisher<T: CommData + Debug, R: Runtime + ?Sized> {
    type SampleMaybeUninit<'a>: SampleMaybeUninit<T, SampleMut: FieldSampleMut<T>> + 'a
    where
        Self: 'a;

    /// Create a new publisher for the specified event source.
    fn new(identifier: &'static str, instance_info: R::ProviderInfo) -> Result<Self>
    where
        Self: Sized;

    /// Get the allocated sample ptr for the field publisher.
    fn allocate(&self) -> Result<Self::SampleMaybeUninit<'_>>;

    /// Update the value of the field with the provided value.
    /// The value is taken by value; the FFI layer handles the necessary copy into the shared
    /// memory slot internally — the same pattern as `Publisher::send(value: T)` for events.
    /// For zero-copy writes use `allocate()` instead.
    fn update(&self, value: T) -> Result<()>;

    /// Register a callback invoked by the middleware whenever a consumer calls the field setter.
    /// The callback receives the proposed new value **by value** and must explicitly return the
    /// value to accept. This allows the callback to validate or modify the proposed value (e.g.
    /// clamping it to a valid range) before it is committed and sent to subscribers.
    ///
    /// This registration is infallible (like `MethodHandler::register_handler`).
    ///
    /// # Parameters
    /// * `callback` - Receives the proposed value and returns the value to accept.
    fn register_set_handler(&self, callback: impl Fn(T) -> T + Send + 'static);

    /// Register a callback invoked by the middleware whenever a consumer calls the field getter.
    /// The callback returns the value that will be delivered back to the consumer.
    ///
    /// Note: In the C++ implementation the default get handler is registered automatically by the
    /// framework (it returns the last `Update`d value). Rust exposes this explicitly so producers
    /// can install custom read logic if needed.
    ///
    /// This registration is infallible (like `MethodHandler::register_handler`).
    ///
    /// # Parameters
    /// * `callback` - The callback function; must return the current field value.
    fn register_get_handler(&self, callback: impl Fn() -> T + Send + 'static);
}

/// FieldSampleMut trait is used to update the value of the field sample for zero-copy API.
pub trait FieldSampleMut<T>: concept::SampleMut<T>
where
    T: CommData + Debug,
{
    /// Update the value for zero-copy API.
    fn update(self) -> Result<()>;
}
