/********************************************************************************
 * Copyright (c) 2025 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * SPDX-License-Identifier: Apache-2.0
 ********************************************************************************/

/// Type-state marker for uninitialized field value state (compile-time tracking).
///
/// These marker types are never constructed as values - they only appear as generic
/// type parameters inside `PhantomData<(S, H)>` on the generated `{Id}Validator` struct
/// (see `TypeStateValidator` in `score_com_macros`). The compiler's `dead_code` lint
/// flags unit structs that are never instantiated, so it is suppressed here deliberately.
#[allow(dead_code)]
pub struct Uninit;

/// Type-state marker for initialized field value state (compile-time tracking).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct Init;

/// Type-state marker for handler not registered (compile-time tracking).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct HandlerNotSet;

/// Type-state marker for handler registered (compile-time tracking).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct HandlerSet;

/// Field capability tag: by adding this on interface macro, consumer can call async `get_*()` on this field.
/// Use in `Field<T, WithGetter>` (or combined: `Field<T, WithGetter + WithSetter + WithNotifier>`).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct WithGetter;

/// Field capability tag: by adding this on interface macro, consumer can call async `set_*()` on this field.
/// Use in `Field<T, WithSetter>` (or combined: `Field<T, WithGetter + WithSetter + WithNotifier>`).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct WithSetter;

/// Field capability tag: by adding this on interface macro, consumer can `subscribe()` to field-value-change notifications.
/// Use in `Field<T, WithNotifier>` (or combined: `Field<T, WithGetter + WithSetter + WithNotifier>`).
/// See [`Uninit`] for why `dead_code` is suppressed.
#[allow(dead_code)]
pub struct WithNotifier;

/// Macro to implement the Consumer trait for a given interface ID and its events.
///
/// Main interface macro that generates Consumer, Producer, and OfferedProducer types
/// along with all necessary trait implementations.
///
/// Supports Event-only interfaces (backward compatible) and mixed interfaces containing
/// any combination of `Event<T>`, `Field<T>`, and `method_name(Args) -> Return` members
/// in the same definition block.
///
/// Automatically generates unique type names from the identifier of macro invocation.
/// For an interface with identifier `{id}`, it generates:
/// - `{id}Interface` - Struct representing the interface with INTERFACE_ID constant
/// - `{id}Consumer<R>` - Consumer implementation with event subscribers, field subscribers,
///   and method callers
/// - `{id}Producer<R>` - Producer implementation
/// - `{id}OfferedProducer<R>` - Offered producer implementation with event publishers,
///   field publishers, and method handlers
/// - Implements the `Interface`, `Consumer`, `Producer`, and `OfferedProducer` traits
///   for the respective types.
/// - `Interface_ID` is generated by default as the module path + interface name,
///   but can be overridden by providing a custom UID as a second parameter to the macro.
///
/// # Member types
/// - `name: Event<T>` - event subscriber / publisher pair
/// - `name: Field<T>` - field subscriber / publisher pair (with set-handler callback support)
/// - `name(Args) -> Return` - method caller / handler pair (fn-like syntax)
///
/// # Parameters
/// - Keywords: `interface` followed by the interface identifier and a block of member definitions.
/// - `$id`: Simple identifier used for type name generation (e.g., Vehicle, Engine)
/// - Members can be any mix of `Event<T>`, `Field<T>`, and `name(Args) -> Return`
///
/// # Example: Event-only with auto-generated ID
/// ```ignore
/// mod abc {
///     use score_com::interface;
///     interface!(
///         interface Vehicle {
///             left_tire: Event<Tire>,
///             exhaust: Event<Exhaust>,
///         }
///     );
/// }
/// ```
/// The generated code will include:
/// - `VehicleInterface` struct with `INTERFACE_ID = "abc::Vehicle"`
/// - `VehicleConsumer<R>` struct that implements `Consumer` trait for subscribing to
///   "left_tire" and "exhaust" events.
/// - `VehicleProducer<R>` struct that implements `Producer` trait for producing
///   "left_tire" and "exhaust" events.
/// - `VehicleOfferedProducer<R>` struct that implements `OfferedProducer` trait for offering
///   "left_tire" and "exhaust" events.
/// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>`
///
/// # Example: Event-only with custom ID
/// ```ignore
/// mod abc {
///     use score_com::interface;
///     interface!(
///         interface Vehicle {
///             Id = "AbcInterface",
///             left_tire: Event<Tire>,
///             exhaust: Event<Exhaust>,
///         }
///     );
/// }
/// ```
/// Here `Id` is explicitly set to `"AbcInterface"` instead of the default `"abc::Vehicle"`.
/// The generated code will include:
/// - `VehicleInterface` struct with `INTERFACE_ID = "AbcInterface"`
/// - `VehicleConsumer<R>` struct that implements `Consumer` trait for subscribing
///   to "left_tire" and "exhaust" events.
/// - `VehicleProducer<R>` struct that implements `Producer` trait for producing
///   "left_tire" and "exhaust" events.
/// - `VehicleOfferedProducer<R>` struct that implements `OfferedProducer` trait for offering
///   "left_tire" and "exhaust" events.
///
/// # Example: Mixed interface (Event + Field + Method) with different field tags
/// ```ignore
/// mod abc {
///     use score_com::interface;
///     interface!(
///         interface Vehicle {
///             Id = "AbcInterface",
///             // Event member
///             left_tire: Event<Tire>,
///             // Field with all three tags: consumer gets subscriber + get caller + set caller
///             tire_pressure: Field<Tire, WithGetter + WithSetter + WithNotifier>,
///             // Field with only WithGetter: consumer gets get caller only
///             speed: Field<Speed, WithGetter>,
///             // Field with only WithNotifier: consumer gets subscriber only
///             status: Field<Status, WithNotifier>,
///             // Method member
///             update_left_tire_pressure(Tire) -> (),
///             // Get method
///             get_tire_pressure() -> Tire,
///         }
///     );
/// }
/// ```
/// The generated code will include:
/// - `VehicleInterface` struct with `INTERFACE_ID = "AbcInterface"`
/// - `VehicleConsumer<R>` with:
///   - `left_tire: Subscriber<Tire>`
///   - `tire_pressure: FieldSubscriber<Tire>` (from `WithNotifier`),
///     `tire_pressure_get: FieldGetCaller<Tire>` (from `WithGetter`),
///     `tire_pressure_set: FieldSetCaller<Tire>` (from `WithSetter`)
///   - `speed_get: FieldGetCaller<Speed>` (from `WithGetter` only — no subscriber)
///   - `status: FieldSubscriber<Status>` (from `WithNotifier` only — no get/set callers)
///   - `update_left_tire_pressure: MethodCaller<(Tire,), Tire>` and a convenience `update_left_tire_pressure(arg0: Tire)` method
///   - `get_tire_pressure: MethodCaller<(), Tire>` and a convenience `get_tire_pressure()` method
/// - `VehicleProducer<R>` derives `TypeStateValidator` and requires the `.init()` chain
///   before `offer()` can be called:
/// ```ignore
/// producer.init()
///     .update_tire_pressure(&initial_value)?
///     .register_set_handler_tire_pressure(|v| { /* handle set */ })
///     .register_get_handler_speed(|| Speed { value: 0 })
///     .update_status(&initial_status)?
///     .register_calibrate_handler(|tire: &Tire| tire.clone())
///     .offer()?;
/// ```
/// - `VehicleOfferedProducer<R>` contains `left_tire: Publisher<Tire>`
///   plus the moved field publishers and the active method handler.
///
/// If the user calls `producer.offer()` directly (without going through `init()`), it will
/// panic at runtime, since the handlers have not been registered yet.
#[macro_export]
macro_rules! interface {
    // Default unique ID based on the module path and interface name
    (interface $id:ident { $($event_name:ident : Event<$event_type:ty>),+ $(,)? }) => {
        $crate::interface_common!($id);
        $crate::interface_consumer!($id, $($event_name, Event<$event_type>),+);
        $crate::interface_producer!($id, $($event_name, Event<$event_type>),+);
    };

    // Custom unique Id provided by the user
    (interface $id:ident {
        Id = $uid:expr,
        $($event_name:ident : Event<$event_type:ty>),+ $(,)?
    }) => {
        $crate::interface_common!($id, $uid);
        $crate::interface_consumer!($id, $($event_name, Event<$event_type>),+);
        $crate::interface_producer!($id, $($event_name, Event<$event_type>),+);
    };

    // This is for backward compatibility for existing users with comma (,)
    (interface $id:ident, {
        Id = $uid:expr,
        $($event_name:ident : Event<$event_type:ty>),+ $(,)?
    }) => {
        $crate::interface! {
            interface $id {
                Id = $uid,
                $($event_name : Event<$event_type>),+
            }
        }
    };

    // Mixed / unified: custom ID
    (interface $id:ident {
        Id = $uid:expr,
        $($members:tt)*
    }) => {
        $crate::interface_common!($id, $uid);
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[]
            @fi[]
            @fi_n[]
            @fi_g[]
            @fi_s[]
            @me[]
            $($members)*
        );
    };

    // Mixed / unified: auto-generated ID
    (interface $id:ident { $($members:tt)* }) => {
        $crate::interface_common!($id);
        $crate::_interface_collect_members!(
            @id[$id, concat!(module_path!(), "::", stringify!($id))]
            @ev[]
            @fi[]
            @fi_n[]
            @fi_g[]
            @fi_s[]
            @me[]
            $($members)*
        );
    };
}

/// Helper for `_interface_collect_members!`.
///
/// Iterates over the tag list of a single field, adding the field to the correct per-tag
/// accumulator list. When all tags are consumed, calls back to `_interface_collect_members!`
/// with the updated lists and the remaining interface members.
#[doc(hidden)]
#[macro_export]
macro_rules! _field_split_tags {
    // Base: all tags consumed - call back to _interface_collect_members! with updated lists
    (
        @ctx[
            @id[$id:ident, $uid:expr]
            @ev[$($ev_name:ident : $ev_type:ty ,)*]
            @fi[$($fi_name:ident : $fi_type:ty ,)*]
            @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
            @rest[$($rest:tt)*]
        ]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @field[$_name:ident : $_t:ty]
        @tags[]
    ) => {
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[$($ev_name : $ev_type ,)*]
            @fi[$($fi_name : $fi_type ,)*]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
            $($rest)*
        );
    };

    // WithNotifier: add field to fi_n list, recurse with remaining tags
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fi_g:tt)*]
        @fi_s[$($fi_s:tt)*]
        @field[$name:ident : $t:ty]
        @tags[WithNotifier $(, $rest_tag:ident)*]
    ) => {
        $crate::_field_split_tags!(
            @ctx[$($ctx)*]
            @fi_n[$($fin_name : $fin_type ,)* $name : $t ,]
            @fi_g[$($fi_g)*]
            @fi_s[$($fi_s)*]
            @field[$name : $t]
            @tags[$($rest_tag),*]
        );
    };

    // WithGetter: add field to fi_g list, recurse with remaining tags
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fi_n:tt)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fi_s:tt)*]
        @field[$name:ident : $t:ty]
        @tags[WithGetter $(, $rest_tag:ident)*]
    ) => {
        $crate::_field_split_tags!(
            @ctx[$($ctx)*]
            @fi_n[$($fi_n)*]
            @fi_g[$($fig_name : $fig_type ,)* $name : $t ,]
            @fi_s[$($fi_s)*]
            @field[$name : $t]
            @tags[$($rest_tag),*]
        );
    };

    // WithSetter: add field to fi_s list, recurse with remaining tags
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fi_n:tt)*]
        @fi_g[$($fi_g:tt)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @field[$name:ident : $t:ty]
        @tags[WithSetter $(, $rest_tag:ident)*]
    ) => {
        $crate::_field_split_tags!(
            @ctx[$($ctx)*]
            @fi_n[$($fi_n)*]
            @fi_g[$($fi_g)*]
            @fi_s[$($fis_name : $fis_type ,)* $name : $t ,]
            @field[$name : $t]
            @tags[$($rest_tag),*]
        );
    };

    // Unrecognized tag
    (
        @ctx[$($ctx:tt)*]
        @fi_n[$($fi_n:tt)*]
        @fi_g[$($fi_g:tt)*]
        @fi_s[$($fi_s:tt)*]
        @field[$name:ident : $_t:ty]
        @tags[$unknown:ident $(, $rest_tag:ident)*]
    ) => {
        compile_error!(concat!(
            "interface!: unrecognized field tag `",
            stringify!($unknown),
            "` on field `",
            stringify!($name),
            "`. Supported tags: WithGetter, WithSetter, WithNotifier."
        ));
    };
}

/// Internal recursive-macro helper for `interface!`.
///
/// Accumulates members into typed lists, then calls the mixed generator macros.
/// Field members MUST carry at least one capability tag: `Field<T, WithGetter + WithSetter + WithNotifier>`.
/// `Field<T>` without tags is a compile error.
/// Tags control which consumer-side infrastructure is generated per field:
///  - `WithGetter`   - `{name}_get: R::FieldGetCaller<T>` + `get_{name}()` async wrapper
///  - `WithSetter`   - `{name}_set: R::FieldSetCaller<T>` + `set_{name}(val)` async wrapper
///  - `WithNotifier` - `{name}: R::FieldSubscriber<T>` (subscribe / notifications)
/// Any combination and any ordering of tags is supported.
///
/// Fields are split into three flat lists during accumulation:
///  @fi_n  - fields with WithNotifier tag (name:type)
///  @fi_g  - fields with WithGetter tag (name:type)
///  @fi_s  - fields with WithSetter tag (name:type)
/// A field with multiple tags appears in multiple lists.
/// The plain @fi list (name:type only) is still kept for forwarding to interface_producer_mixed!.
#[doc(hidden)]
#[macro_export]
macro_rules! _interface_collect_members {
    // Base case: nothing left - emit the mixed consumer and producer.
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $(,)?
    ) => {
        $crate::interface_consumer_mixed!(
            $id,
            events[$($ev_name : $ev_type ,)*],
            fields_notifier[$($fin_name : $fin_type ,)*],
            fields_getter[$($fig_name : $fig_type ,)*],
            fields_setter[$($fis_name : $fis_type ,)*],
            methods[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
        );
        $crate::interface_producer_mixed!(
            $id,
            events[$($ev_name : $ev_type ,)*],
            fields[$($fi_name : $fi_type ,)*],
            fields_setter[$($fis_name : $fis_type ,)*],
            fields_getter[$($fig_name : $fig_type ,)*],
            methods[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
        );
    };

    // Event member: `name : Event<T> ,?`
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident : Event<$t:ty>
        $(, $($rest:tt)*)?
    ) => {
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[$($ev_name : $ev_type ,)* $name : $t ,]
            @fi[$($fi_name : $fi_type ,)*]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
            $($($rest)*)?
        );
    };

    // Field member WITH tags: `name : Field<T, Tag1 + Tag2 + ...> ,?`
    // Delegates to _field_split_tags! to distribute the field into the per-tag flat lists.
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident : Field<$t:ty, $first_tag:ident $(+ $rest_tag:ident)*>
        $(, $($rest:tt)*)?
    ) => {
        $crate::_field_split_tags!(
            @ctx[
                @id[$id, $uid]
                @ev[$($ev_name : $ev_type ,)*]
                @fi[$($fi_name : $fi_type ,)* $name : $t ,]
                @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)*]
                @rest[$($($rest)*)?]
            ]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @field[$name : $t]
            @tags[$first_tag $(, $rest_tag)*]
        );
    };

    // Field member WITHOUT tags: `name : Field<T> ,?`  compile error.
    (
        @id[$_id:ident, $_uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident : Field<$_t:ty>
        $(, $($rest:tt)*)?
    ) => {
        compile_error!(concat!(
            "interface!: Field member `",
            stringify!($name),
            "` requires at least one capability tag.\n",
            "Supported tags: WithGetter, WithSetter, WithNotifier\n",
            "Use the `+` syntax to combine tags, e.g.:\n",
            "  ", stringify!($name), ": Field<T, WithGetter + WithSetter + WithNotifier>\n",
            "  ", stringify!($name), ": Field<T, WithGetter>\n",
            "  ", stringify!($name), ": Field<T, WithSetter>\n",
            "  ", stringify!($name), ": Field<T, WithNotifier>\n",
            "Tags control which consumer-side infrastructure is generated:\n",
            "  WithGetter   - get_*()\n",
            "  WithSetter   - set_*()\n",
            "  WithNotifier - subscribe()\n",
        ));
    };

    // Method member (fn-like syntax): `name(Arg0, Arg1, ...) -> Ret ,?`
    (
        @id[$id:ident, $uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $name:ident ( $($arg_ty:ty),* ) -> $ret:ty
        $(, $($rest:tt)*)?
    ) => {
        $crate::_interface_collect_members!(
            @id[$id, $uid]
            @ev[$($ev_name : $ev_type ,)*]
            @fi[$($fi_name : $fi_type ,)*]
            @fi_n[$($fin_name : $fin_type ,)*]
            @fi_g[$($fig_name : $fig_type ,)*]
            @fi_s[$($fis_name : $fis_type ,)*]
            @me[$($me_name [$($me_arg_ty),*] -> $me_ret ,)* $name [$($arg_ty),*] -> $ret ,]
            $($($rest)*)?
        );
    };

    // Catch-all: unrecognized member - emit a clear compile-time error.
    (
        @id[$_id:ident, $_uid:expr]
        @ev[$($ev_name:ident : $ev_type:ty ,)*]
        @fi[$($fi_name:ident : $fi_type:ty ,)*]
        @fi_n[$($fin_name:ident : $fin_type:ty ,)*]
        @fi_g[$($fig_name:ident : $fig_type:ty ,)*]
        @fi_s[$($fis_name:ident : $fis_type:ty ,)*]
        @me[$($me_name:ident [$($me_arg_ty:ty),*] -> $me_ret:ty ,)*]
        $($unknown:tt)+
    ) => {
        compile_error!(concat!(
            "interface!: unrecognized member syntax: `",
            stringify!($($unknown)+),
            "`.\n",
            "Supported member types:\n",
            "  name: Event<T>                                           - event subscriber / publisher pair\n",
            "  name: Field<T, WithGetter + WithSetter + WithNotifier>   - field with capability tags\n",
            "  name(Arg0, Arg1, ...) -> Ret                             - method caller / handler pair\n",
            "Note: Field<T> without tags is not allowed. Specify at least one of:\n",
            "  WithGetter, WithSetter, WithNotifier\n",
            "Example:\n",
            "  interface!(interface MyIface {\n",
            "      my_event: Event<MyData>,\n",
            "      my_field: Field<MyData, WithGetter + WithSetter + WithNotifier>,\n",
            "      my_method(MyData) -> MyData,\n",
            "  });"
        ));
    };
}

/// Macro to create a unique interface struct and implement the Interface trait for it.
///
/// Generates the INTERFACE_ID constant and associated Consumer/Producer types.
/// INTERFACE_ID is generated by default as the module path + interface name,
/// but can be overridden by providing a custom UID as a second parameter to the macro.
#[macro_export]
macro_rules! interface_common {
    // Default: auto ID = module path + type name
    ($id:ident) => {
        score_com::paste::paste! {
            pub struct [<$id Interface>] {}
            impl score_com::Interface for [<$id Interface>] {
                const INTERFACE_ID: &'static str =
                    concat!(module_path!(), "::", stringify!($id));
                type Consumer<R: score_com::Runtime + ?Sized> = [<$id Consumer>]<R>;
                type Producer<R: score_com::Runtime + ?Sized> = [<$id Producer>]<R>;
            }
        }
    };
    // Explicit ID override
    ($id:ident, $uid:expr) => {
        score_com::paste::paste! {
            pub struct [<$id Interface>] {}
            impl score_com::Interface for [<$id Interface>] {
                const INTERFACE_ID: &'static str = $uid;
                type Consumer<R: score_com::Runtime + ?Sized> = [<$id Consumer>]<R>;
                type Producer<R: score_com::Runtime + ?Sized> = [<$id Producer>]<R>;
            }
        }
    };
}

mod tests {
    /// ```
    /// mod my_module {
    ///     use score_com::{interface,CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire: Event<Tire>,
    ///             exhaust: Event<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will generate the following types and trait implementations:
    /// - `VehicleInterface` struct with `INTERFACE_ID = "my_module::Vehicle"`
    /// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>` with appropriate
    ///   trait implementations for the Vehicle interface.
    #[cfg(doctest)]
    fn interface_macro_with_auto_id() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///            Id = "CustomVehicleInterface",
    ///             left_tire: Event<Tire>,
    ///             exhaust: Event<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will generate the following types and trait implementations:
    /// - `VehicleInterface` struct with `INTERFACE_ID = "CustomVehicleInterface"`
    /// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>` with appropriate
    ///   trait implementations for the Vehicle interface.
    #[cfg(doctest)]
    fn interface_macro_with_custom_id() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle, {
    ///            Id = "CustomVehicleInterface",
    ///             left_tire: Event<Tire>,
    ///             exhaust: Event<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will generate the following types and trait implementations:
    /// - `VehicleInterface` struct with `INTERFACE_ID = "CustomVehicleInterface"`
    /// - `VehicleConsumer<R>`, `VehicleProducer<R>`, `VehicleOfferedProducer<R>` with appropriate
    ///   trait implementations for the Vehicle interface.
    #[cfg(doctest)]
    fn interface_macro_with_custom_id_with_comma_for_backend_compatibility() {}

    /// Mixed interface (Event + Field + Method) with a custom ID.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithGetter, WithSetter, WithNotifier};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             Id = "AbcInterface",
    ///             left_tire: Event<Tire>,
    ///             left_tire_field: Field<Tire, WithGetter + WithSetter + WithNotifier>,
    ///             left_tire_method(Tire) -> Tire,
    ///         }
    ///     );
    /// }
    /// ```
    /// Generates `VehicleInterface`, `VehicleConsumer<R>`, `VehicleProducer<R>`,
    /// and `VehicleOfferedProducer<R>` where:
    /// - `VehicleConsumer<R>` has `left_tire: Subscriber<Tire>`,
    ///   `left_tire_field: FieldSubscriber<Tire>` (from `WithNotifier`),
    ///   `left_tire_field_get: FieldGetCaller<Tire>` (from `WithGetter`),
    ///   `left_tire_field_set: FieldSetCaller<Tire>` (from `WithSetter`),
    ///   `left_tire_method: MethodCaller<(Tire,), Tire>`,
    ///   and a convenience `left_tire_method(arg0: Tire)` method.
    /// - `VehicleProducer<R>` derives `TypeStateValidator` and requires the `.init()` chain:
    ///   `producer.init().update_left_tire_field(&val)?.register_set_handler_left_tire_field(f).register_left_tire_method_handler(h).offer()?`
    /// - `VehicleOfferedProducer<R>` has `left_tire: Publisher<Tire>` (created lazily on offer),
    ///   `left_tire_field: FieldPublisher<Tire>`, plus the active method handler.
    #[cfg(doctest)]
    fn interface_macro_mixed() {}

    /// Field with `WithNotifier` only  consumer can subscribe to value-change notifications.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithNotifier};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire_field: Field<Tire, WithNotifier>,
    ///         }
    ///     );
    /// }
    /// ```
    /// Generates:
    /// - `VehicleConsumer<R>` has `left_tire_field: FieldSubscriber<Tire>`.
    /// - `VehicleOfferedProducer<R>` has `left_tire_field: FieldPublisher<Tire>`.
    /// No `_get` or `_set` callers are generated on the consumer side.
    ///
    /// `WithNotifier`-only fields do not generate a `register_set_handler_*` step:
    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, WithNotifier};
    ///     #[derive(Debug, Reloc, Clone)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire { const ID: &'static str = "Tire"; }
    ///     score_com::interface!(interface Vehicle { left_tire_field: Field<Tire, WithNotifier>, });
    ///     fn _check<R: score_com::Runtime + ?Sized>(p: VehicleProducer<R>) {
    ///         let _ = p.init().register_set_handler_left_tire_field(|v: Tire| v);
    ///     }
    /// }
    /// ```
    ///
    /// `WithNotifier`-only fields do not generate a `register_get_handler_*` step:
    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, WithNotifier};
    ///     #[derive(Debug, Reloc, Clone)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire { const ID: &'static str = "Tire"; }
    ///     score_com::interface!(interface Vehicle { left_tire_field: Field<Tire, WithNotifier>, });
    ///     fn _check<R: score_com::Runtime + ?Sized>(p: VehicleProducer<R>) {
    ///         let _ = p.init().register_get_handler_left_tire_field(|| Tire { pressure: 0.0 });
    ///     }
    /// }
    /// ```
    #[cfg(doctest)]
    fn interface_macro_field_with_notifier_only() {}

    /// Field with `WithGetter` only  consumer can call async `get_*()`.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithGetter,
    ///                     LolaRuntimeImpl as LolaRuntime};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire_field: Field<Tire, WithGetter>,
    ///         }
    ///     );
    ///
    ///     // Compile-time check `register_get_handler_*` exists for WithGetter fields.
    ///     #[allow(dead_code)]
    ///     fn _check_get_handler(p: VehicleProducer<LolaRuntime>) {
    ///         let _ = p.init().register_get_handler_left_tire_field(|| Tire { pressure: 0.0 });
    ///     }
    /// }
    /// ```
    /// Generates:
    /// - `VehicleConsumer<R>` has `left_tire_field_get: FieldGetCaller<Tire>`.
    /// - `VehicleOfferedProducer<R>` has `left_tire_field: FieldPublisher<Tire>`.
    /// No subscriber or `_set` caller is generated on the consumer side.
    ///
    /// `WithGetter`-only fields do not generate a `register_set_handler_*` step:
    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, WithGetter};
    ///     #[derive(Debug, Reloc, Clone)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire { const ID: &'static str = "Tire"; }
    ///     score_com::interface!(interface Vehicle { left_tire_field: Field<Tire, WithGetter>, });
    ///     fn _check<R: score_com::Runtime + ?Sized>(p: VehicleProducer<R>) {
    ///         let _ = p.init().register_set_handler_left_tire_field(|v: Tire| v);
    ///     }
    /// }
    /// ```
    #[cfg(doctest)]
    fn interface_macro_field_with_getter_only() {}

    /// Field with `WithSetter` only  consumer can call async `set_*()`.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithSetter,
    ///                     LolaRuntimeImpl as LolaRuntime};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire_field: Field<Tire, WithSetter>,
    ///         }
    ///     );
    ///
    ///     // Compile-time check `register_set_handler_*` exists for WithSetter fields.
    ///     #[allow(dead_code)]
    ///     fn _check_set_handler(p: VehicleProducer<LolaRuntime>) {
    ///         let _ = p.init().register_set_handler_left_tire_field(|v: Tire| v);
    ///     }
    /// }
    /// ```
    /// Generates:
    /// - `VehicleConsumer<R>` has `left_tire_field_set: FieldSetCaller<Tire>`.
    /// - `VehicleOfferedProducer<R>` has `left_tire_field: FieldPublisher<Tire>`.
    /// No subscriber or `_get` caller is generated on the consumer side.
    ///
    /// `WithSetter`-only fields do not generate a `register_get_handler_*` step:
    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, WithSetter};
    ///     #[derive(Debug, Reloc, Clone)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire { const ID: &'static str = "Tire"; }
    ///     score_com::interface!(interface Vehicle { left_tire_field: Field<Tire, WithSetter>, });
    ///     fn _check<R: score_com::Runtime + ?Sized>(p: VehicleProducer<R>) {
    ///         let _ = p.init().register_get_handler_left_tire_field(|| Tire { pressure: 0.0 });
    ///     }
    /// }
    /// ```
    #[cfg(doctest)]
    fn interface_macro_field_with_setter_only() {}

    /// Field with `WithGetter + WithNotifier`  consumer can both get and subscribe.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithGetter, WithNotifier};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire_field: Field<Tire, WithGetter + WithNotifier>,
    ///         }
    ///     );
    /// }
    /// ```
    /// Generates:
    /// - `VehicleConsumer<R>` has `left_tire_field: FieldSubscriber<Tire>` (from `WithNotifier`)
    ///   and `left_tire_field_get: FieldGetCaller<Tire>` (from `WithGetter`).
    /// - `VehicleOfferedProducer<R>` has `left_tire_field: FieldPublisher<Tire>`.
    /// No `_set` caller is generated.
    #[cfg(doctest)]
    fn interface_macro_field_with_getter_and_notifier() {}

    /// Field with `WithSetter + WithNotifier`  consumer can both set and subscribe.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithSetter, WithNotifier};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire_field: Field<Tire, WithSetter + WithNotifier>,
    ///         }
    ///     );
    /// }
    /// ```
    /// Generates:
    /// - `VehicleConsumer<R>` has `left_tire_field: FieldSubscriber<Tire>` (from `WithNotifier`)
    ///   and `left_tire_field_set: FieldSetCaller<Tire>` (from `WithSetter`).
    /// - `VehicleOfferedProducer<R>` has `left_tire_field: FieldPublisher<Tire>`.
    /// No `_get` caller is generated.
    #[cfg(doctest)]
    fn interface_macro_field_with_setter_and_notifier() {}

    /// Field with `WithGetter + WithSetter`  consumer can both get and set, without notifications.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithGetter, WithSetter,
    ///                     LolaRuntimeImpl as LolaRuntime};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire_field: Field<Tire, WithGetter + WithSetter>,
    ///         }
    ///     );
    ///
    ///     // Compile-time proof: both handler methods exist for WithGetter + WithSetter fields.
    ///     #[allow(dead_code)]
    ///     fn _assert_both_handlers(p: VehicleProducer<LolaRuntime>) {
    ///         let v = p.init().register_set_handler_left_tire_field(|v: Tire| v);
    ///         let _ = v.register_get_handler_left_tire_field(|| Tire { pressure: 0.0 });
    ///     }
    /// }
    /// ```
    /// Generates:
    /// - `VehicleConsumer<R>` has `left_tire_field_get: FieldGetCaller<Tire>` (from `WithGetter`)
    ///   and `left_tire_field_set: FieldSetCaller<Tire>` (from `WithSetter`).
    /// - `VehicleOfferedProducer<R>` has `left_tire_field: FieldPublisher<Tire>`.
    /// No subscriber is generated (no `WithNotifier`).
    #[cfg(doctest)]
    fn interface_macro_field_with_getter_and_setter() {}

    /// Multiple fields with different tag combinations on the same interface.
    ///
    /// ```
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher,
    ///                     FieldPublisher, WithGetter, WithSetter, WithNotifier};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             notify_only_field: Field<Tire, WithNotifier>,
    ///             get_only_field: Field<Tire, WithGetter>,
    ///             set_only_field: Field<Tire, WithSetter>,
    ///             get_set_field: Field<Tire, WithGetter + WithSetter>,
    ///             get_notify_field: Field<Tire, WithGetter + WithNotifier>,
    ///             set_notify_field: Field<Tire, WithSetter + WithNotifier>,
    ///             full_field: Field<Tire, WithGetter + WithSetter + WithNotifier>,
    ///         }
    ///     );
    /// }
    /// ```
    /// Each field generates only the consumer-side accessors for its declared tags:
    /// - `notify_only_field`: subscriber only.
    /// - `get_only_field`: `_get` caller only.
    /// - `set_only_field`: `_set` caller only.
    /// - `get_set_field`: `_get` and `_set` callers, no subscriber.
    /// - `get_notify_field`: `_get` caller and subscriber, no `_set`.
    /// - `set_notify_field`: `_set` caller and subscriber, no `_get`.
    /// - `full_field`: subscriber, `_get` caller, and `_set` caller.
    /// All fields get a `FieldPublisher<Tire>` on the producer side regardless of tags.
    #[cfg(doctest)]
    fn interface_macro_field_all_tag_combinations() {}

    /// Using an unrecognized field tag is a compile-time error.
    ///
    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///             left_tire_field: Field<Tire, WithReadOnly>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This fails to compile because `WithReadOnly` is not a recognized field tag.
    /// Supported tags are: `WithGetter`, `WithSetter`, `WithNotifier`.
    #[cfg(doctest)]
    fn interface_macro_field_unrecognized_tag() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///
    ///     interface!(
    ///         interface Vehicle {
    ///            Id = "CustomVehicleInterface",
    ///             left_tire: Method<Tire>,
    ///             exhaust: Method<Exhaust>,
    ///         }
    ///     );
    /// }
    /// ```
    /// This will fail to compile because `Method<T>` (old syntax without a return type) is not
    /// supported. Use fn-like syntax: `method_name(Args) -> Ret`.
    #[cfg(doctest)]
    fn interface_macro_with_old_method_syntax() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Event<Tire>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because `interface_common!` does not accept member definitions.
    /// Use `interface!` for a complete interface definition.
    #[cfg(doctest)]
    fn interface_macro_with_Field() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface_common, interface_consumer, interface_producer};
    ///     use score_com::{CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle);
    ///     interface_consumer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    ///     interface_producer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleInterface` struct with an `INTERFACE_ID` constant that is
    /// automatically generated as the module path plus
    /// the interface name (e.g."my_module::Vehicle").
    /// It will also define associated `Consumer` and `Producer` types for the `VehicleInterface`.
    /// The `VehicleConsumer<R>` struct will implement the `Consumer` trait for the
    /// `VehicleInterface`, with subscribers for the `left_tire` and `exhaust` events.
    /// The `VehicleProducer<R>` struct will implement the `Producer` trait for the
    /// `VehicleInterface`, with publishers for the `left_tire` and `exhaust` events.
    #[cfg(doctest)]
    fn individual_common_macro_with_auto_id() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface_common, interface_consumer, interface_producer};
    ///     use score_com::{CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle, "CustomVehicleInterface");
    ///     interface_consumer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    ///     interface_producer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleInterface` struct with an `INTERFACE_ID` constant set to
    /// "CustomVehicleInterface".
    /// It will also define associated `Consumer` and `Producer` types for the `VehicleInterface`.
    /// The `VehicleConsumer<R>` struct will implement the `Consumer` trait for the
    /// `VehicleInterface`, with subscribers for the `left_tire` and `exhaust` events.
    /// The `VehicleProducer<R>` struct will implement the `Producer` trait for the
    /// `VehicleInterface`, with publishers for the `left_tire` and `exhaust` events.
    #[cfg(doctest)]
    fn individual_macro_with_custom_id() {}

    /// ```compile_fail
    /// mod my_module {
    ///      use score_com::{interface_common, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///      #[derive(Debug, Reloc)]
    ///      #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///    impl CommData for Tire {
    ///        const ID: &'static str = "Tire";
    ///   }
    ///     #[derive(Debug, Reloc)]
    ///    #[repr(C)]
    ///   pub struct Exhaust {}
    ///   impl CommData for Exhaust {
    ///       const ID: &'static str = "Exhaust";
    ///   }
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Event<Tire>,
    ///         exhaust: Event<Exhaust>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because the `interface_common!` macro does not accept event
    /// definitions and will produce a compile-time error indicating that the macro does not support
    /// event definitions.
    #[cfg(doctest)]
    fn interface_common_macro_with_events() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_common, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Method<Tire>,
    ///         exhaust: Method<Exhaust>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because the `interface_common!` macro does not accept method
    /// definitions and will produce a compile-time error indicating that the macro does not support
    /// method definitions.
    #[cfg(doctest)]
    fn interface_common_macro_with_methods() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_common, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_common!(Vehicle, "CustomVehicleInterface", {
    ///         left_tire: Field<Tire>,
    ///         exhaust: Field<Exhaust>,
    ///     });
    /// }
    /// ```
    /// This will fail to compile because the `interface_common!` macro does not accept field
    /// definitions and will produce a compile-time error indicating
    /// that the macro does not support field definitions.
    #[cfg(doctest)]
    fn interface_common_macro_with_fields() {}

    /// ```
    /// mod my_module {
    ///     use score_com::{interface_consumer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_consumer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleConsumer<R>` struct that implements the `Consumer` trait for
    /// the `VehicleInterface`, with subscribers for the `left_tire` and `exhaust` events.
    /// The generated `VehicleConsumer<R>` struct will have fields for each event subscriber, and
    /// the `new` method will initialize these subscribers using
    /// the runtime's `Subscriber::new` method.
    /// The macro will also include error handling to ensure that subscriber creation failures are
    /// properly reported.
    #[cfg(doctest)]
    fn interface_consumer_macro() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_consumer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_consumer!(Vehicle, left_tire, Method<Tire>, exhaust, Method<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_consumer!` macro does not support Method
    /// definitions and will produce a compile-time error indicating that
    /// Method definitions are not supported.
    #[cfg(doctest)]
    fn interface_consumer_macro_with_Method() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_consumer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_consumer!(Vehicle, left_tire, Field<Tire>, exhaust, Field<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_consumer!` macro does not support Field
    /// definitions and will produce a compile-time error indicating that
    /// Field definitions are not supported.
    #[cfg(doctest)]
    fn interface_consumer_macro_with_Field() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_producer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_producer!(Vehicle, left_tire, Event<Tire>, exhaust, Event<Exhaust>);
    /// }
    /// ```
    /// This will generate a `VehicleProducer<R>` struct that implements the `Producer` trait for
    /// the `VehicleInterface`, with publishers for the `left_tire` and `exhaust` events.
    /// So it requires interface_common macro to be called before to generate
    /// the VehicleInterface struct
    /// and implement the Interface trait for it.
    #[cfg(doctest)]
    fn interface_producer_macro() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_producer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_producer!(Vehicle, left_tire, Method<Tire>, exhaust, Method<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_producer!` macro does not support Method
    /// definitions and will produce a compile-time error indicating that
    /// Method definitions are not supported.
    #[cfg(doctest)]
    fn interface_producer_macro_with_Method() {}

    /// ```compile_fail
    /// mod my_module {
    ///     use score_com::{interface_producer, CommData, Reloc, ProviderInfo, Subscriber, Publisher};
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Tire { pub pressure: f32 }
    ///     impl CommData for Tire {
    ///         const ID: &'static str = "Tire";
    ///     }
    ///
    ///     #[derive(Debug, Reloc)]
    ///     #[repr(C)]
    ///     pub struct Exhaust {}
    ///     impl CommData for Exhaust {
    ///         const ID: &'static str = "Exhaust";
    ///     }
    ///     interface_producer!(Vehicle, left_tire, Field<Tire>, exhaust, Field<Exhaust>);
    /// }
    /// ```
    /// This will fail to compile because the `interface_producer!` macro does not support Field
    /// definitions and will produce a compile-time error indicating that
    /// Field definitions are not supported.
    #[cfg(doctest)]
    fn interface_producer_macro_with_Field() {}
}

#[cfg(test)]
#[allow(dead_code)]
#[allow(unused_imports)]
mod validation_tests {
    #[test]
    fn test_interface_id_auto_generated() {
        mod test_module {
            use score_com::{CommData, ProviderInfo, Publisher, Reloc, Subscriber};

            #[derive(Debug, Reloc)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            score_com::interface!(
                interface Vehicle {
                    left_tire: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing VehicleInterface by name is itself proof the type was generated;
                // the compiler enforces the name at compile time.
                let interface_id = <VehicleInterface as score_com::Interface>::INTERFACE_ID;
                let expected_id = concat!(module_path!(), "::", "Vehicle");
                assert_eq!(
                    interface_id, expected_id,
                    "Interface ID mismatch for VehicleInterface"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_consumer_type_generated() {
        mod test_module {
            use score_com::{
                CommData, Consumer, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Exhaust {
                pub temp: f32,
            }
            impl CommData for Exhaust {
                const ID: &'static str = "Exhaust";
            }

            score_com::interface!(
                interface Vehicle {
                    left_tire: Event<Tire>,
                    exhaust: Event<Exhaust>,
                }
            );

            pub fn validate() {
                // Referencing VehicleConsumer<LolaRuntime> by name is proof the type was generated.
                // The size check verifies that subscriber fields were generated.
                assert!(
                    std::mem::size_of::<VehicleConsumer<LolaRuntime>>() > 0,
                    "VehicleConsumer should have subscriber fields"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_producer_type_generated() {
        mod test_module {
            use score_com::{
                CommData, LolaRuntimeImpl as LolaRuntime, Producer, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            score_com::interface!(
                interface Engine {
                    rpm: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing EngineProducer<LolaRuntime> by name is proof the type was generated.
                let _ = core::marker::PhantomData::<EngineProducer<LolaRuntime>>;
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_offered_producer_type_generated() {
        mod test_module {
            use score_com::{
                CommData, LolaRuntimeImpl as LolaRuntime, Producer, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            score_com::interface!(
                interface Transmission {
                    gear: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing TransmissionOfferedProducer<LolaRuntime> by name is proof the type
                // was generated.
                // The size check verifies that publisher fields were generated.
                assert!(
                    std::mem::size_of::<TransmissionOfferedProducer<LolaRuntime>>() > 0,
                    "TransmissionOfferedProducer should have publisher fields"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_with_custom_id_validation() {
        mod test_module {
            use score_com::{CommData, Interface, ProviderInfo, Publisher, Reloc, Subscriber};

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            score_com::interface!(
                interface Battery, {
                    Id = "com.example.Battery",
                    voltage: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing BatteryInterface by name is proof the type was generated with the
                // correct naming convention; the custom ID is a meaningful runtime assertion.
                let interface_id = <BatteryInterface as Interface>::INTERFACE_ID;
                assert_eq!(
                    interface_id, "com.example.Battery",
                    "Custom interface ID should match provided UID"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_with_multiple_events_validation() {
        mod test_module {
            use score_com::{
                CommData, Interface, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher,
                Reloc, Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Event1Data {
                pub value: i32,
            }
            impl CommData for Event1Data {
                const ID: &'static str = "Event1Data";
            }

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Event2Data {
                pub value: f64,
            }
            impl CommData for Event2Data {
                const ID: &'static str = "Event2Data";
            }

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Event3Data {
                pub value: bool,
            }
            impl CommData for Event3Data {
                const ID: &'static str = "Event3Data";
            }

            score_com::interface!(
                interface MultiEvent {
                    event_one: Event<Event1Data>,
                    event_two: Event<Event2Data>,
                    event_three: Event<Event3Data>,
                }
            );

            pub fn validate() {
                // ID assertion is meaningful at runtime.
                let interface_id = <MultiEventInterface as Interface>::INTERFACE_ID;
                assert_eq!(
                    interface_id,
                    concat!(module_path!(), "::", "MultiEvent"),
                    "Interface ID should be auto-generated from module path and interface name"
                );

                // Referencing Consumer, Producer, and OfferedProducer by name proves all four
                // types were generated, the compiler enforces the names at compile time.
                let _ = core::marker::PhantomData::<MultiEventConsumer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<MultiEventProducer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<MultiEventOfferedProducer<LolaRuntime>>;
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_type_consistency_across_traits() {
        mod test_module {
            use score_com::{
                CommData, Interface, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher,
                Reloc, Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Tire {
                pub pressure: f32,
            }
            impl CommData for Tire {
                const ID: &'static str = "Tire";
            }

            score_com::interface!(
                interface Suspension {
                    travel: Event<Tire>,
                }
            );

            pub fn validate() {
                // Referencing all four generated types by their expected names is proof of
                // consistent naming, the compiler enforces the names at compile time.
                let _ = core::marker::PhantomData::<SuspensionInterface>;
                let _ = core::marker::PhantomData::<SuspensionConsumer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<SuspensionProducer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<SuspensionOfferedProducer<LolaRuntime>>;

                let interface_id = <SuspensionInterface as Interface>::INTERFACE_ID;
                assert_eq!(
                    interface_id,
                    concat!(module_path!(), "::", "Suspension"),
                    "Interface ID should be auto-generated from module path and interface name"
                );
            }
        }
        test_module::validate();
    }

    #[test]
    fn test_interface_naming_convention_validation() {
        mod test_module {
            use score_com::{
                CommData, LolaRuntimeImpl as LolaRuntime, ProviderInfo, Publisher, Reloc,
                Subscriber,
            };

            #[derive(Debug, Reloc, Clone)]
            #[repr(C)]
            pub struct Data {
                pub value: u32,
            }
            impl CommData for Data {
                const ID: &'static str = "Data";
            }

            score_com::interface!(
                interface ABS {
                    status: Event<Data>,
                }
            );

            pub fn validate() {
                // Referencing each generated type by its expected name is itself the proof of
                // correct naming conventions, the compiler enforces the names at compile time.
                // Pattern: {Name}Interface, {Name}Consumer, {Name}Producer, {Name}OfferedProducer
                let _ = core::marker::PhantomData::<ABSInterface>;
                let _ = core::marker::PhantomData::<ABSConsumer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<ABSProducer<LolaRuntime>>;
                let _ = core::marker::PhantomData::<ABSOfferedProducer<LolaRuntime>>;
            }
        }
        test_module::validate();
    }
}
